version: '2.32.4'
services:
  mongo:
    container_name: mongo-prueba
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
        - mongodata:/data/db
  frontend: 
    container_name: frontend-docker
    image: frontend-docker:0.0.1
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8000:8000
  backend: 
    container_name: backend-docker
    image: backend-docker:0.0.1
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
volumes:
  mongodata:
    driver: local